package edu.nwtc.chat.client;

import javax.swing.JFrame;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author tsmeester
 */
public class Chat extends javax.swing.JPanel {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	protected JFrame parent;
	protected ChatClient client;

	/**
	 * Creates new form Chat
	 */
	public Chat(JFrame parent, ChatClient client) {
		this.parent = parent;
		this.client = client;
		initComponents();
		parent.setContentPane(this);
		parent.setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		txtConversation = new javax.swing.JTextArea();
		client.setMessageArea(txtConversation);
		txtChat = new javax.swing.JTextField();
		
		txtSend = new javax.swing.JButton();
		txtSend.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				String message = txtChat.getText();
				client.sendMessage(message);
			}
		});
		
		txtQuit = new javax.swing.JButton();
		txtQuit.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				System.exit(0);
			}
		});

		setBackground(new java.awt.Color(204, 204, 204));
		setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		txtConversation.setColumns(20);
		txtConversation.setRows(5);
		jScrollPane1.setViewportView(txtConversation);

		txtSend.setText("Send");

		txtQuit.setText("Quit");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(jScrollPane1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
						.addGroup(layout.createSequentialGroup()
							.addComponent(txtChat)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
								.addComponent(txtSend, GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
								.addComponent(txtQuit, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
					.addGap(42))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
							.addComponent(txtSend)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(txtQuit))
						.addComponent(txtChat, GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
					.addContainerGap())
		);
		this.setLayout(layout);
	}// </editor-fold>

	// Variables declaration - do not modify
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField txtChat;
	private javax.swing.JTextArea txtConversation;
	private javax.swing.JButton txtQuit;
	private javax.swing.JButton txtSend;
	// End of variables declaration
}
