/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.nwtc.chat.client;
import java.awt.event.ActionListener;

import javax.swing.JFrame;

import java.awt.event.ActionEvent;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author tsmeester
 */
public class Login extends javax.swing.JPanel {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	protected JFrame parent;
	protected Messages messages;

	/**
	 * Creates new form NewJPanel
	 */
	public Login(JFrame parent, Messages messages) {
		initComponents();
		this.parent = parent;
		this.messages = messages;
		parent.setContentPane(this);
		parent.setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		txtScreenName = new javax.swing.JTextField();
		txtAddress = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		btnLogin = new javax.swing.JButton();
		btnLogin.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				txtScreenNameActionPerformed(e);
			}
		});
		btnCancel = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();

		setBackground(new java.awt.Color(204, 204, 204));
		setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		txtScreenName.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtScreenNameActionPerformed(evt);
			}
		});

		jLabel1.setText(messages.getString("Login.0")); //$NON-NLS-1$

		jLabel2.setText(messages.getString("Login.1")); //$NON-NLS-1$

		btnLogin.setText(messages.getString("Login.2")); //$NON-NLS-1$
		btnLogin.setPreferredSize(new java.awt.Dimension(75, 28));

		btnCancel.setText(messages.getString("Login.3")); //$NON-NLS-1$
		btnCancel.setName(messages.getString("Login.4")); // NOI18N //$NON-NLS-1$
		btnCancel.setPreferredSize(new java.awt.Dimension(75, 28));
		btnCancel.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCancelActionPerformed(evt);
			}
		});

		jLabel3.setFont(new java.awt.Font(messages.getString("Login.5"), 0, 36)); // NOI18N //$NON-NLS-1$
		jLabel3.setText(messages.getString("Login.6")); //$NON-NLS-1$
		
		JLabel lblPassword = new JLabel(messages.getString("Login.7")); //$NON-NLS-1$
		
		passwordField = new JPasswordField();
		
		JLabel lblPortblankFor = new JLabel(messages.getString("Login.8")); //$NON-NLS-1$
		
		txtPort = new JTextField();
		txtPort.setColumns(10);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
							.addComponent(jLabel1)
							.addContainerGap(187, Short.MAX_VALUE))
						.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
							.addComponent(lblPassword)
							.addContainerGap(204, Short.MAX_VALUE))
						.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
							.addComponent(jLabel2)
							.addContainerGap(176, Short.MAX_VALUE))
						.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
							.addComponent(lblPortblankFor)
							.addContainerGap(140, Short.MAX_VALUE))
						.addGroup(layout.createSequentialGroup()
							.addComponent(jLabel3)
							.addContainerGap(65, Short.MAX_VALUE))
						.addGroup(layout.createSequentialGroup()
							.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
								.addComponent(txtPort, Alignment.LEADING)
								.addComponent(txtAddress, Alignment.LEADING)
								.addComponent(passwordField, Alignment.LEADING)
								.addComponent(txtScreenName, Alignment.LEADING)
								.addGroup(Alignment.LEADING, layout.createSequentialGroup()
									.addComponent(btnLogin, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
									.addPreferredGap(ComponentPlacement.RELATED)
									.addComponent(btnCancel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
							.addContainerGap())))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addComponent(jLabel3)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(jLabel1)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(txtScreenName, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(lblPassword)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(passwordField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(jLabel2)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(txtAddress, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(lblPortblankFor)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(txtPort, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(btnLogin, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(btnCancel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addContainerGap())
		);
		this.setLayout(layout);

		getAccessibleContext().setAccessibleDescription(messages.getString("Login.9")); //$NON-NLS-1$
	}// </editor-fold>

	private void txtScreenNameActionPerformed(java.awt.event.ActionEvent evt) {
		doLogin();
	}

	private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {
		System.exit(0);
	}
	
	private void doLogin() {
		String name = txtScreenName.getText();
		char[] password = passwordField.getPassword();
		String address = txtAddress.getText();
		String port = txtPort.getText();
		ChatClient chatClient = null;
		if (port != null && !messages.getString("Login.10").equals(port)) { //$NON-NLS-1$
			chatClient = new ChatClient(name, password, address, Integer.parseInt(port));
		} else {
			chatClient = new ChatClient(name, password, address);
		}
		chatClient.start();
		
		Chat chat = new Chat(parent, messages, chatClient);
		parent.setContentPane(chat);
		parent.setVisible(true);
	}

	// Variables declaration - do not modify
	private javax.swing.JButton btnCancel;
	private javax.swing.JButton btnLogin;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JTextField txtAddress;
	private javax.swing.JTextField txtScreenName;
	private JPasswordField passwordField;
	private JTextField txtPort;
}
